name: Build ShellyForHA
on:
  workflow_dispatch:
    
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: StyraHem/ShellyForHASS
    - name: Replace domain
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: "DOMAIN = 'shelly'"
        replace: "DOMAIN = 'shelly4ha'"
        include: 'custom_components/shelly/const.py'
        regex: false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: custom_components/shelly/frontend/package-lock.json
    - run: node --version
      working-directory: custom_components/shelly/frontend
    - run: npm ci
      working-directory: custom_components/shelly/frontend
    - run: npm install --global rollup
    - run: rollup -c
      working-directory: custom_components/shelly/frontend
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        directory: custom_components/shelly
        type: 'zip'
        filename: '../../shelly4ha.zip'
        exclusions: '*.git* /frontend/*'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        name: "Release ${{ github.REF }}"
        draft: true
        tag: ${{ github.REF }}
        artifacts: "shelly4ha.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
